// instance.hpp — generated by ref/gen_instance.py (deterministic). NO REAL KEYS.
#pragma once
#include <cstdint>
constexpr uint32_t TOY_P = 4294966177u;
constexpr uint32_t TOY_Gx = 1960037684u;
constexpr uint32_t TOY_Gy = 560815139u;
constexpr uint64_t TOY_L  = 4294835173ull;
