#!/usr/bin/env python3
"""ref.py — independent reference for toy-ECDLP curves (y^2 = x^3 + 7 mod p).
Computes the REAL group order #E (BSGS over Hasse trace interval), finds a base
point G of prime order l, and emits instance.hpp + a DLP test vector file for the
C++ lab to consume. Pure Python big-int. Deterministic. NO real keys/wallets.
"""
import sys, random, math

P32M5  = 4294967291   # 2^32-5
P32M99 = 4294967197   # 2^32-99 (p=1 mod 3)

def modinv(a, m): return pow(a, -1, m)

def on_curve(P, p): return P is not None and (P[0]**3 + 7 - P[1]**2) % p == 0

def add(P, Q, p):
    if P is None: return Q
    if Q is None: return P
    x1, y1 = P; x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % p == 0: return None
        l = 3 * x1 * x1 % p * modinv(2 * y1, p) % p
    else:
        l = (y2 - y1) % p * modinv((x2 - x1) % p, p) % p
    x3 = (l * l - x1 - x2) % p
    y3 = (l * (x1 - x3) - y1) % p
    return (x3, y3)

def mul(k, P, p):
    R = None; Q = P
    while k:
        if k & 1: R = add(R, Q, p)
        Q = add(Q, Q, p)
        k >>= 1
    return R

def sqrt_mod(a, p):
    if a == 0: return 0
    assert p % 4 == 3, "TS general not needed for these p"
    return pow(a, (p + 1) // 4, p)

def rand_point(p):
    while True:
        x = random.randrange(0, p)
        rhs = (x**3 + 7) % p
        y = sqrt_mod(rhs, p)
        if y * y % p == rhs:
            return (x, y)

def group_order(p):
    """Return exact #E(F_p) via BSGS on the Hasse trace t.
    #E = p+1-t, |t| <= 2*sqrt(p)."""
    B = math.isqrt(4 * p) + 1                 # Hasse bound for 2*sqrt(p) factor
    P = rand_point(p)                          # random point, order divides #E
    Q = mul(p + 1, P, p)                       # = t*P  (since (p+1-t) P = O)
    # solve t*P = Q with |t| <= B. Shift t = s - B', s in [0, 2B].
    R = 2 * B
    m = math.isqrt(R) + 1
    baby = {}
    cur = None
    for a in range(m):
        baby[cur] = a
        cur = P if cur is None else add(cur, P, p)
    # giant: X_b = Q + (b*m - B)*P ; want X_b in baby -> t = B - (b*m - a)
    step = mul(m, P, p)
    mB = mul(B, P, p)
    gbase = (mB[0], (-mB[1]) % p)             # -(B*P)  (negate ONLY y)
    giant = add(Q, gbase, p)
    sol = None
    for b in range(m + 1):
        idx = baby.get(giant)
        if idx is not None:
            t = B - (b * m - idx)
            if p + 1 - t >= 0:
                sol = t
                break
        giant = add(giant, step, p)
    assert sol is not None, "trace search failed"
    N = p + 1 - sol
    # verify with two more independent random points
    for _ in range(2):
        P2 = rand_point(p)
        assert mul(N, P2, p) is None, "order verification failed"
    return N

def is_prime(n):
    if n < 2: return False
    for s in (2,3,5,7,11,13,17,19,23,29,31,37):
        if n % s == 0: return n == s
    d, r = n - 1, 0
    while d % 2 == 0: d //= 2; r += 1
    for _ in range(40):
        a = 2 + random.randrange(n - 3)
        x = pow(a, d, n)
        if x in (1, n - 1): continue
        for _ in range(r - 1):
            x = x * x % n
            if x == n - 1: break
        else: return False
    return True

def largest_prime_factor(n):
    m = n
    f = 1
    d = 2
    while d * d <= m:
        while m % d == 0:
            m //= d; f = d
        d += 1
    if m > 1: f = m
    return f

def prime_order_point(p, N):
    l = largest_prime_factor(N)
    assert is_prime(l), "largest factor not prime"
    for _ in range(1000):
        P = rand_point(p)
        # P has order d | N. G = (N/l)*P has order dividing l.
        G = mul(N // l, P, p)
        if G is not None and mul(l, G, p) is None and on_curve(G, p):
            return G, l
    raise RuntimeError("no generator found")

def main():
    random.seed(20260922)
    lines_hpp = ["// instance.hpp — generated by ref/ref.py (deterministic). HEADER ONLY.", "#pragma once"]
    lines_vec = []
    for name, p in (("P32M5", P32M5), ("P32M99", P32M99)):
        N = group_order(p)
        G, l = prime_order_point(p, N)
        print(f"CURVE {name} p={p}")
        print(f"  #E = {N}   (= p+1-t)")
        print(f"  generator order l = {l}  (prime)")
        # DLP test vectors: random interval-lifted k in [1, 1<<20)
        for iv in (16, 20):
            ks = random.randrange(1, 1 << iv)
            Q = mul(ks, G, p)
            print(f"  DLP lvl{iv}: k={ks} Q={Q}")
            lines_vec.append(f"{name} {iv} {ks} {Q[0]} {Q[1]}")
        lines_hpp.append(f"constexpr uint32_t P_{name} = {p}u;")
        lines_hpp.append(f"// #E = {N}, generator G=({G[0]},{G[1]}) order l={l}")
        lines_hpp.append(f"constexpr uint32_t Gx_{name} = {G[0]}u;")
        lines_hpp.append(f"constexpr uint32_t Gy_{name} = {G[1]}u;")
        lines_hpp.append(f"constexpr uint64_t L_{name} = {l}ull;")
    with open("instance.hpp", "w") as f:
        f.write("\n".join(lines_hpp) + "\n")
    with open("dlp_vectors.txt", "w") as f:
        f.write("\n".join(lines_vec) + "\n")
    print("wrote instance.hpp and dlp_vectors.txt")

if __name__ == "__main__":
    main()