#!/usr/bin/env python3
"""pn2_maxtrace.py — OPEN probe PN-2 (near-max-trace slab).

Query: D = -3*2419^2 with t/2sqrt(p) ≈ 0.9995. Does the relation between the CM
fundamental domain and the interval DLP leak sub-sqrt structure? Measure, honestly,
the geometric quantity that would have to collapse for a shortcut: the reduced
GLV coefficients (k1,k2) for k in [0,2^db) — specifically their typical norm vs
sqrt(N) and their location in the fundamental domain.

Prediction (from E1): the interval maps to a wide lattice region; |(k1,k2)| tracks
sqrt(l) not sqrt(N) for db<=14, and for db>=16 exactly the non-trivial k2 appears but
the 2D grid must be searched at scale ~ sqrt(l)/sqrt(2) — no lattice width collapse.
If a collapse WERE measured (|k1|,|k2| ~ sqrt(N) for ALL k<N), that would be CLASS-4
territory. We expect REFUTED (no collapse).
"""
import io, os, sys, math, random, csv

sys.stdout.reconfigure(encoding="utf-8"); sys.stderr.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path[:0] = [HERE]
from gen import TOY_P, TOY_L, TOY_G

P, L, G = TOY_P, TOY_L, (TOY_G[0], TOY_G[1])

# cube root of unity mod p (theta): omega = (-1 + sqrt(-3))/2  (root of x^2+x+1)
def tonelli(n, p):
    """sqrt(n) mod p for prime p; p=4294966177 confirmed prime."""
    if p % 4 == 3:
        r = pow(n, (p + 1) // 4, p)
        return r if (r * r) % p == n % p else None
    # generic Tonelli-Shanks
    q, s = p - 1, 0
    while q % 2 == 0:
        q //= 2; s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1:
        z += 1
    m, c, t, r = s, pow(z, q, p), pow(n, q, p), pow(n, (q + 1) // 2, p)
    while t != 1:
        i, t2 = 0, t
        while t2 != 1:
            t2 = (t2 * t2) % p; i += 1
        b = pow(c, 1 << (m - i - 1), p)
        m, c, t, r = i, (b * b) % p, (t * b * b) % p, (r * b) % p
    return r if (r * r) % p == n % p else None

def cube_root_unity(p):
    s = tonelli((-3) % p, p)
    if s is None:
        return None
    w = ((-1 + s) * pow(2, -1, p)) % p   # (-1+sqrt(-3))/2
    return w if (w * w + w + 1) % p == 0 else ((w * w) % p)

def lam_eig(l):
    # phi: (x,y)->(THETA x, y); phi(G)=lambda G. lambda^2+lambda+1=0 mod l.
    # Solve via quadratic formula mod l (l prime).
    s = tonelli((-3) % l, l)
    if s is None:
        return None
    lam = ((-1 + s) * pow(2, -1, l)) % l
    return lam if (lam * lam + lam + 1) % l == 0 else ((-lam - 1) % l)

THETA = cube_root_unity(P)
LAM = lam_eig(L)

def gauss_2d(a, b):
    """Gauss reduction of 2D lattice spanned by vectors a,b (tuples of ints).
    Returns short basis vectors u,v."""
    while True:
        if a[0]*a[0] + a[1]*a[1] > b[0]*b[0] + b[1]*b[1]:
            a, b = b, a
        # b -= round((a.b)/(a.a)) * a
        num = a[0]*b[0] + a[1]*b[1]
        den = a[0]*a[0] + a[1]*a[1]
        q = round(num / den) if den else 0
        if q == 0:
            return a, b
        b = (b[0] - q*a[0], b[1] - q*a[1])

def glv_decompose(k, lam, l, N):
    """Return (k1,k2) with k1 + k2*lam == k (mod l), |k1|,|k2| ~ sqrt(l) via 2D
    Gauss-reduced lattice of the GLV relations lattice (generated by (lam,1),(l,0))."""
    v1 = (lam, 1)
    v2 = (l, 0)
    u, v = gauss_2d(v1, v2)
    # nearest-plane: reduce target (k,0) by the two short basis vectors
    x, y = k, 0
    for base in (u, v):
        num = x*base[0] + y*base[1]
        den = base[0]*base[0] + base[1]*base[1]
        q = round(num / den)
        x -= q*base[0]
        y -= q*base[1]
    # (x,y) = (k,0) - q*u - r*v ; each lattice elem (d1,d2) satisfies d1 ≡ d2*lam (mod l).
    # k = x + ... => k1 = ...  With u,v in the relations lattice, (k - d1 - d2*lam) ≡ k (mod l) kept:
    d1, d2 = k - x, -y
    # d1 + d2*lam ≡ k (mod l) because (x,y) has x ≡ -y*lam? check: (x,y) = (k,0) - (q*u + r*v),
    # and q*u+r*v is in relations lattice => its first coord ≡ second*lam (mod l).
    k1 = (d1 - d2*lam) % l
    if k1 > l//2: k1 -= l
    # canonical: k1 is small now
    return k1, -d2

def main():
    lab = os.path.join(HERE, "lab"); os.makedirs(lab, exist_ok=True)
    rng = random.Random(20260931)
    rows = []
    print("theta(cube root mod p) =", THETA, " lam(mod l, root of x^2+x+1) =", LAM)
    dbs = [10, 12, 14, 16, 18, 20, 22, 24, 26]
    print("== PN-2: interval -> reduced GLV coefficients (k1,k2); width check ==")
    for db in dbs:
        N = 1 << db
        ns = max(3, min(20, (1 << 26) // N))  # sample count inversely with N to bound runtime
        maxn1 = maxn2 = 0
        avg = 0.0; cnt = 0
        for _ in range(ns):
            k = rng.randrange(1, N)
            k1, k2 = glv_decompose(k, LAM, L, N)
            maxn1 = max(maxn1, abs(k1)); maxn2 = max(maxn2, abs(k2))
            avg += (k1*k1 + k2*k2); cnt += 1
        avg_norm = math.sqrt(avg / cnt) if cnt else 0.0
        sN = math.sqrt(N); sl = math.sqrt(L)
        collapsed = (maxn1 < sN and maxn2 < sN)
        rows.append([db, N, ns, maxn1, maxn2, "%.1f" % avg_norm,
                     "%.1f" % sN, "%.1f" % sl, int(collapsed)])
        print("db=%2d N=2^%d max|k1|=%-8d max|k2|=%-8d avg|(k1,k2)|=%-8.1f sqrtN=%-8.1f sqrtl=%-7.1f collapsed=%s"
              % (db, db, maxn1, maxn2, avg_norm, sN, sl, collapsed))
    with io.open(os.path.join(lab, "PN2_MAXTRACE.csv"), "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["db","N","samples","max_k1","max_k2","avg_norm","sqrt_N","sqrt_l","lattice_collapsed"])
        for r in rows: w.writerow(r)
    print("WROTE lab/PN2_MAXTRACE.csv")

if __name__ == "__main__":
    main()